# Auto-generated function from symbolic regression
# Predicts SHEAR STRESS from acoustic emission parameters
# Generated by PySR - Symbolic Regression
# Best Equation (Complexity 17): R² Score 1.47e-06

import numpy as np

def predict_shear_stress(RISE, COUN, ENER, DURATION, AMP):
    """
    Predict shear stress from acoustic emission parameters using discovered equation.
    
    This equation was discovered through symbolic regression on acoustic emission
    data from rock shear testing. It represents a non-linear relationship involving
    logarithmic transforms and power law relationships.
    
    Parameters:
    -----------
    RISE : float or array
        Rise time of acoustic emission signal (units: microseconds)
    COUN : float or array
        Count of acoustic emission events (units: number)
    ENER : float or array
        Energy of acoustic emission (units: V*sample)
    DURATION : float or array
        Duration of acoustic emission signal (units: microseconds)
    AMP : float or array
        Amplitude of acoustic emission signal (units: dB)
    
    Returns:
    --------
    shear_stress : float or array
        Predicted shear stress (units: MPa)
    
    Examples:
    ---------
    >>> # Single prediction
    >>> stress = predict_shear_stress(12.5, 450, 1250, 85.3, 45.2)
    
    >>> # Batch prediction with arrays
    >>> import numpy as np
    >>> rise = np.array([12.5, 15.0, 10.2])
    >>> amp = np.array([45.2, 48.5, 42.1])
    >>> stress = predict_shear_stress(rise, 450, 1250, 85.3, amp)
    """
    # Discovered Equation (Best for accuracy-complexity tradeoff):
    # SHEAR_STRESS = (0.99492353 ^ ENER) + abs(sqrt(log(square(AMP + RISE) + square(DURATION - AMP))))
    #
    # Physical Interpretation:
    # - Exponential term: (0.99492353^ENER) ≈ weak exponential decay with energy
    # - Logarithmic term: log(...) acts as damping/compression of large values
    # - Pythagorean form: sqrt(x²+y²) relates amplitude and duration interactions
    # - Absolute value ensures non-negative stress predictions
    
    term1 = 0.99492353 ** ENER
    
    amp_rise = AMP + RISE
    duration_amp = DURATION - AMP
    
    pythagorean = np.sqrt(amp_rise**2 + duration_amp**2)
    logarithmic = np.log(pythagorean)
    
    term2 = np.abs(np.sqrt(logarithmic))
    
    shear_stress = term1 + term2
    
    return shear_stress


def predict_with_confidence(RISE, COUN, ENER, DURATION, AMP, model_rmse=3.526):
    """
    Predict shear stress with confidence interval.
    
    Parameters:
    -----------
    RISE, COUN, ENER, DURATION, AMP : float or array
        Input acoustic emission parameters
    model_rmse : float
        Root Mean Squared Error of the model (default: 3.526 from test set)
    
    Returns:
    --------
    predictions : dict
        Dictionary with keys: 'prediction', 'lower_bound', 'upper_bound'
    """
    prediction = predict_shear_stress(RISE, COUN, ENER, DURATION, AMP)
    std_error = model_rmse
    
    return {
        'prediction': prediction,
        'lower_bound': prediction - 1.96 * std_error,  # 95% CI
        'upper_bound': prediction + 1.96 * std_error,
        'model_rmse': model_rmse
    }


if __name__ == '__main__':
    # Example usage and validation
    print("Shear Stress Prediction Function")
    print("="*50)
    
    # Example 1: Single prediction
    result = predict_shear_stress(12.5, 450, 1250, 85.3, 45.2)
    print(f"\nExample 1 - Single prediction:")
    print(f"Input: RISE=12.5, COUN=450, ENER=1250, DURATION=85.3, AMP=45.2")
    print(f"Predicted Shear Stress: {result:.4f} MPa")
    
    # Example 2: With confidence intervals
    conf = predict_with_confidence(12.5, 450, 1250, 85.3, 45.2)
    print(f"\nExample 2 - With 95% Confidence Interval:")
    print(f"Prediction: {conf['prediction']:.4f} MPa")
    print(f"95% CI: [{conf['lower_bound']:.4f}, {conf['upper_bound']:.4f}] MPa")
    
    # Example 3: Batch predictions
    import numpy as np
    rise_vals = np.array([10, 12.5, 15, 20])
    amp_vals = np.array([40, 45.2, 50, 55])
    results = predict_shear_stress(rise_vals, 450, 1250, 85.3, amp_vals)
    print(f"\nExample 3 - Batch prediction (4 samples):")
    for i, (r, stress) in enumerate(zip(rise_vals, results)):
        print(f"  Sample {i+1}: RISE={r}, AMP={amp_vals[i]} → Stress={stress:.4f} MPa")
